### ISSUE TITLE
Title should not be required field

### ISSUE THREAD

**Issue by zoranlorkovic** [laravel-notification-channels/gcm#11]
And currently we cannot notification without title value because line 75 in GcmChannel.php

$packet->setCollapseKey(str_slug($message->title));

As it says in GCM documentation, title isn't required for iOS but it is for Android.

https://developers.google.com/cloud-messaging/http-server-ref

**Comment by dwightwatson** [comment]
Forgive me because I'm new to GCM but I've just been having a read-over of the documentation.

First off, it sounds like the collapse key is optional - do you think instead we should have developers provide a collapse key if they want instead of trying to infer it automatically?

Otherwise would it be reasonable to perhaps concatenate the title and body and then MD5 them to generate the collapse key? At least one of those parameters is required so it means we'll always have a value for the key.

**Comment by atymic** [comment]
Closing as the package is deprecated
