### ISSUE TITLE
Does this package support FCM ? if so please update readme how to use it 

### ISSUE THREAD

**Issue by mmehdibalouchi** [laravel-notification-channels/gcm#21]

**Comment by prashantidealittechno** [comment]
Can we add FCM in laravel-notification-channels

Firebase Cloud Messaging (FCM) is the new version of GCM. It inherits the reliable and scalable GCM infrastructure, plus new features! See the FAQ to learn more. If you are integrating messaging in a new app, start with FCM. GCM users are strongly recommended to upgrade to FCM, in order to benefit from new FCM features today and in the future. Before you go, please visit our GCM and FCM developer survey to give us feedback!

**Comment by atymic** [comment]
New package will be released here:
https://github.com/laravel-notification-channels/fcm

**Comment by vonec** [comment]
is this package released?
